#
# Use nix-emacs-ci for travis CI
# URL: https://github.com/purcell/nix-emacs-ci
#

language: nix

os:
  - linux

env:
  - EMACS_CI=emacs-27-1

install:
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  - make test
